### PR TITLE
Add/slim

### PR DESCRIPTION
**Pull request by kaczmarj**
Hi @vsoch - this PR is in response to #2. I preserved as much as possible from the original Dockerfile. One change is that I install to `/usr/local/singularity` instead of `/usr/local`. That makes sure that only singularity files are copied over, and not other things installed to `/usr/local`.

One question: when you `git clone` singularity, we checkout to `release-3.0`. Should this be the case? Or should we checkout to the 3.0.2 tag?

### CODE REVIEW

**Comment by vsoch** [comment]
Good question! This branch was created based off of the 3.0 branch, for which we are grabbing the release-3.0 branch from singularityware, which (at some future point) could be updated. For the sub versions  (e.g., 3.0.2) we don't have branches so we grab the official releases, for example see the [3.0.2](https://github.com/singularityhub/singularity-docker/blob/3.0.2/Dockerfile#L33) Dockerfile that does this. So if you like you can copy those lines to get the official 3.0.2 release (since it appears that sylabs isn't creating branches for the subversions). 

Changing to /usr/local sounds good to me :)

**Comment by vsoch** [comment]
hey @kaczmarj just wanted to follow up - did you see my comment above? If you want to change to use the release for 3.0.2 we should be good to go :) Let me know if you need any help.

**Comment by kaczmarj** [comment]
I think I got it!

**Comment by vsoch** [comment]
Looks good! Merging.

**Pull request merged**
