### PR TITLE
Fix singularity-ce 4 build

### PR DESCRIPTION
**Pull request by emi80**
Hi everybody,

this PR fixes the build for singualrity-ce v4 with the following changes:

* update base image to use `go 1.21.3`
* bump singularity version to `4.0.1`
* add missing dependencies (`autoconf` and `fuse3-dev`)
* fix `--virtual` option usage 

I think the Docker file might also be cleaned up and improved a bit if you like.

### CODE REVIEW

**Comment by marcodelapierre** [comment]
Hi @vsoch , I believe this PR from my colleague Emilio would enable the build of the container images for Singularity v4.0, which are currently failing due to the `go` interpreter not being found. As such, it seems a super useful PR! 😄

**Comment by vsoch** [comment]
Thank you! It came in after 1am so I couldn't respond then (and it's still just 6am now).

The main Dockerfile looks good - @emi80 would you please also update the Dockerfile.arm?

And I hugely appreciate the help - I took a stab at the update and it failed the build (and didn't have time to come back to it)!

**Comment by vsoch** [comment]
@emi80 that particular commit is added, but I fell back to 4.0.0 because you opened to that branch. Before we do 4.0.1 we need to:

1. Figure out why the Dockerfile.arm is not building, most recent build is here: https://github.com/singularityhub/singularity-docker/actions/runs/6617018704/job/17972454428
2. Create the 4.0.0 slim variant

Then we can move on to 4.0.1. Let me know what you'd like to tackle, and thanks again for the help.

**Comment by emi80** [comment]
Hi @vsoch, thanks a lot!

You are right about versioning. I went directly with 4.0.1 as it is a patch, but I did not think about the branch name.

I just opened another PR for `Dockerfile.arm`. We can continue the discussion there.

Cheers,
Emilio

**Comment by pditommaso** [comment]
What a team!

**Comment by vsoch** [comment]
@pditommaso your emoji game... still strong! 

I'm still working on ARM - almost there I think (but missing a dependency). Here is the current: https://github.com/singularityhub/singularity-docker/actions/runs/6619309200.

When that build works we can use it as a base for the slim images and then 4.0.1. @emi80 I'm happy to take whatever contribution you'd like to give, and I'm happy to do it too. I can ping here when the arm build is working again.

**Comment by vsoch** [comment]
ok I think they are all done: https://github.com/singularityhub/singularity-docker/actions I didn't update the README, can do that next time.

**Comment by marcodelapierre** [comment]
Fantastic @vsoch! 

Question: what is the missing bit to get the version 4.0 image on Quay?  
https://quay.io/repository/singularity/docker2singularity?tab=tags

Or maybe this is now just the wait time until the build goes through the CI queue?

**Comment by vsoch** [comment]
Probably just to use the right container :wink: 

https://quay.io/repository/singularity/singularity?tab=tags

docker2singularity is a different tool, one which hopefully people don't need anymore given you can pull docker down to singularity.

**Comment by vsoch** [comment]
If you do want to use that one, it's here: https://github.com/singularityhub/docker2singularity

I probably should keep updating it - this one build is the first time I was delinquent because it didn't build.

**Comment by marcodelapierre** [comment]
> Probably just to use the right container 😉
> 
> https://quay.io/repository/singularity/singularity?tab=tags

ahah good point! when I was going through this thread, I accidentally searched the wrong Quay repo .. all sorted out, cheers! 😄

**Comment by vsoch** [comment]
I'll have the other one ready soon too though! https://github.com/singularityhub/docker2singularity/pull/131

**Pull request merged**
